import DashboardSidebar from "@/components/featured/dashboard/components/dashboard-sidebar";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DashboardSidebar>
        {children}
    </DashboardSidebar>
  );
}
